// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9mt7C708LjUL1YjmVp9pCv4Eq-CTfyDI',
    appId: '1:188123597154:web:a90f274f76525754d0043b',
    messagingSenderId: '188123597154',
    projectId: 'mindrium-e0099',
    authDomain: 'mindrium-e0099.firebaseapp.com',
    storageBucket: 'mindrium-e0099.firebasestorage.app',
    measurementId: 'G-EBYKSGSSZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBvDHpIU2E5obME_ieIPh0UzrdHfrh38k',
    appId: '1:188123597154:android:291b45ec35335bdcd0043b',
    messagingSenderId: '188123597154',
    projectId: 'mindrium-e0099',
    storageBucket: 'mindrium-e0099.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu0HF1feoGYmE3LEglIjlFRNqFvItZlA4',
    appId: '1:188123597154:ios:6eb9ed651a7267efd0043b',
    messagingSenderId: '188123597154',
    projectId: 'mindrium-e0099',
    storageBucket: 'mindrium-e0099.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCu0HF1feoGYmE3LEglIjlFRNqFvItZlA4',
    appId: '1:188123597154:ios:6eb9ed651a7267efd0043b',
    messagingSenderId: '188123597154',
    projectId: 'mindrium-e0099',
    storageBucket: 'mindrium-e0099.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9mt7C708LjUL1YjmVp9pCv4Eq-CTfyDI',
    appId: '1:188123597154:web:735be40e7b4ab0c7d0043b',
    messagingSenderId: '188123597154',
    projectId: 'mindrium-e0099',
    authDomain: 'mindrium-e0099.firebaseapp.com',
    storageBucket: 'mindrium-e0099.firebasestorage.app',
    measurementId: 'G-E127Z9VRPJ',
  );
}
